### ISSUE TITLE
How to install socialist?!

### ISSUE THREAD

**Issue by TomCosta** [doron2402/socialist#1]
Hey!
I'm a newbie developer using Ionic.
But I heard about MongoDb + Neo4J.
I would like to try it, and put to work.
Please, how may I install it?
Can you give some tip?
Thanks in advance!

**Comment by doron2402** [comment]
Hi @TomCosta ,

the best and easiest way to use docker containers, you can use Docker compose it will make everything much easier:

``` javascript
mongodb:
  image: mongo
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"
neo4j:
image: tpires/neo4j
environment:
 - NEO4J_AUTH: username:password
cap_add:
 - SYS_RESOURCE
ports:
- "7474:7474"
web:
  build: .
  command: node app.js
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - mongodb
    - neo4j
  environment:
    PORT: 3000
```
